import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1779957241024 implements MigrationInterface {
    name = 'InitSchema1779957241024'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`notifications_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`notifications_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`report_images\` DROP FOREIGN KEY \`report_images_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`reports_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`reports_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`reports_ibfk_3\``);
        await queryRunner.query(`DROP INDEX \`username\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`report_id\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`report_id\` ON \`report_images\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`reports\``);
        await queryRunner.query(`DROP INDEX \`category_id\` ON \`reports\``);
        await queryRunner.query(`DROP INDEX \`status_id\` ON \`reports\``);
        await queryRunner.query(`CREATE TABLE \`temp_users\` (\`tempUserId\` int NOT NULL AUTO_INCREMENT, \`fullName\` varchar(100) NOT NULL, \`username\` varchar(100) NOT NULL, \`email\` varchar(100) NOT NULL, \`password\` varchar(255) NOT NULL, \`otpCode\` varchar(6) NOT NULL, \`otpExpiresAt\` datetime NOT NULL, \`isVerified\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_6a18a3e42ff2deecdbbb92e1d4\` (\`email\`), PRIMARY KEY (\`tempUserId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`full_name\` \`full_name\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password\` \`password\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_image\` \`profile_image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('Citizen', 'Admin') NOT NULL DEFAULT 'Citizen'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`report_id\` \`report_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`message\` \`message\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`is_read\` \`is_read\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`report_id\` \`report_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`image_url\` \`image_url\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`uploaded_at\` \`uploaded_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`status\` CHANGE \`status_name\` \`status_name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`category_id\` \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`status_id\` \`status_id\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`title\` \`title\` varchar(150) NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`location\` \`location\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`created_at\` \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`updated_at\` \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`category_name\` \`category_name\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_412af9b32c6225fe444454597f9\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`report_images\` ADD CONSTRAINT \`FK_9560cc9fd5449c70a6e4c42017c\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_ca7a21eb95ca4625bd5eaef7e0c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_23d2ada1e9df0834c42df8d0fb0\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`FK_d71af40d9136c7264578670a0f9\` FOREIGN KEY (\`status_id\`) REFERENCES \`status\`(\`status_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_d71af40d9136c7264578670a0f9\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_23d2ada1e9df0834c42df8d0fb0\``);
        await queryRunner.query(`ALTER TABLE \`reports\` DROP FOREIGN KEY \`FK_ca7a21eb95ca4625bd5eaef7e0c\``);
        await queryRunner.query(`ALTER TABLE \`report_images\` DROP FOREIGN KEY \`FK_9560cc9fd5449c70a6e4c42017c\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_412af9b32c6225fe444454597f9\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`image_url\` \`image_url\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`category_name\` \`category_name\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`created_at\` \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`location\` \`location\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`title\` \`title\` varchar(150) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`status_id\` \`status_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`category_id\` \`category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reports\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`status\` CHANGE \`status_name\` \`status_name\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`uploaded_at\` \`uploaded_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`image_url\` \`image_url\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`report_images\` CHANGE \`report_id\` \`report_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`created_at\` \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`is_read\` \`is_read\` tinyint NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`message\` \`message\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`report_id\` \`report_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('Citizen', 'Admin') NULL DEFAULT ''Citizen''`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`date_of_birth\` \`date_of_birth\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profile_image\` \`profile_image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`password\` \`password\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`full_name\` \`full_name\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP INDEX \`IDX_6a18a3e42ff2deecdbbb92e1d4\` ON \`temp_users\``);
        await queryRunner.query(`DROP TABLE \`temp_users\``);
        await queryRunner.query(`CREATE INDEX \`status_id\` ON \`reports\` (\`status_id\`)`);
        await queryRunner.query(`CREATE INDEX \`category_id\` ON \`reports\` (\`category_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`reports\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`report_id\` ON \`report_images\` (\`report_id\`)`);
        await queryRunner.query(`CREATE INDEX \`report_id\` ON \`notifications\` (\`report_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`notifications\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`username\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`reports_ibfk_3\` FOREIGN KEY (\`status_id\`) REFERENCES \`status\`(\`status_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`reports_ibfk_2\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`category_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`reports\` ADD CONSTRAINT \`reports_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`report_images\` ADD CONSTRAINT \`report_images_ibfk_1\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`notifications_ibfk_2\` FOREIGN KEY (\`report_id\`) REFERENCES \`reports\`(\`report_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`notifications_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

}
